version: "3.9"

services:
  web:
    build: .
    environment:
      DEBUG: "${DEBUG}"
      SECRET_KEY: "${SECRET_KEY}"
    # command: ./start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8888:8888"
